### ISSUE TITLE
Inf is not definied

### ISSUE THREAD

**Issue by Ash-Pera** [ftherrien/p2ptrans#17]
When running p2ptrans on the BCC and FCC structures from the example in the documentation, it fails partially through the crystallography section with 

``` Traceback (most recent call last):
   File "/home/snowcrash/.local/bin/p2ptrans", line 183, in <module>
     main()
   File "/home/snowcrash/.local/bin/p2ptrans", line 142, in main
     eigval, U, P, Q, planeHab = analysis.crystallography(la.inv(tmat), B, A, ccell2, ccell1, planehkl,
   File "/home/snowcrash/.local/lib/python3.8/site-packages/p2ptrans/analysis.py", line 157, in crystallography
     planeHab, ratio = findHabit(U, P, eigval)
   File "/home/snowcrash/.local/lib/python3.8/site-packages/p2ptrans/analysis.py", line 100, in findHabit
     ratio = Inf
 NameError: name 'Inf' is not defined
```

if you change it to `np.inf` (which is what I believe you intended), it instead errors out with 
```
Approximate low index OR
/home/snowcrash/.local/lib/python3.8/site-packages/p2ptrans/utils.py:60: RuntimeWarning: invalid value encountered in true_divide
  min_uvw[:,l] = min_uvw[:,l]/gcd3
Traceback (most recent call last):
  File "/home/snowcrash/.local/bin/p2ptrans", line 183, in <module>
    main()
  File "/home/snowcrash/.local/bin/p2ptrans", line 142, in main
    eigval, U, P, Q, planeHab = analysis.crystallography(la.inv(tmat), B, A, ccell2, ccell1, planehkl,
  File "/home/snowcrash/.local/lib/python3.8/site-packages/p2ptrans/analysis.py", line 191, in crystallography
    print("(+): (% 2d, % 2d, % 2d) [% 2d, % 2d, % 2d] //  (% d, % d, % d) [% d, % d, % d]"%(*planehkl, *diruvw, *resPlanehklClose[0,:], *resDiruvwClose[0,:]))
ValueError: cannot convert float NaN to integer
```

Since I feel like it's unlikely that you introduced this error without noticing it, I suspect it's an environmental issue (I'm on Ubuntu WSL2). I'll do some replication testing

**Comment by ftherrien** [comment]
Hi @Ash-Pera thanks so much for raising this issue! You are right that it should be `np.inf`. I was trying to solve this issue quickly for Vladan and I did not do my due diligence... The second error is because findR() needs to be modified as well to handle the infinite ratio.

**Comment by ftherrien** [comment]
@Ash-Pera, let me know if that fixes it for you, I will close the issue if you confirm.

**Comment by Ash-Pera** [comment]
It appears to be fixed on my end as well, closing.
