### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by yanyuan55** [ftherrien/p2ptrans#21]
Dear all

I am trying to install p2ptrans. Even though I tried in my windows computer, supercomputer, and MacBook, all of them failed. 
The error occurs when Building wheel for p2ptrans (PEP 517) and pylada.

The following is a part of the error information. Does it seem I used the wrong vision of FORTRAN? Could you please give me more suggestions on how to install it correctly?

Best
Yuan

ERROR: Command errored out with exit status 1:
   command: 'D:\software\PyCharm_Community_Edition\project\thankyou\venv\Scripts\python.exe' 'D:\software\PyCharm_Community_Edition\project\thankyou\venv\l
ib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' build_wheel 'C:\Users\35884\AppData\Local\Temp\tmp57lvm3_o'
       cwd: C:\Users\35884\AppData\Local\Temp\pip-install-uzaf822v\pylada_c0102c6f43ea4b54846477eba0124932
  Complete output (104 lines):
  Not searching for unused variables given on the command line.
  -- The CXX compiler identification is MSVC 19.31.31104.0
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: D:/VC2022/Enterprise/VC/Tools/MSVC/14.31.31103/bin/Hostx86/x64/cl.exe - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- The Fortran compiler identification is GNU 6.3.0
  -- Detecting Fortran compiler ABI info
  -- Detecting Fortran compiler ABI info - done
  -- Check for working Fortran compiler: C:/MinGW/bin/gfortran.exe - skipped
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/35884/AppData/Local/Temp/pip-install-uzaf822v/pylada_c0102c6f43ea4b54846477eba0124932/_cmake_test_compile/b
uild
  -- The C compiler identification is MSVC 19.31.31104.0
  -- The CXX compiler identification is MSVC 19.31.31104.0
  -- The Fortran compiler identification is GNU 6.3.0
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: D:/VC2022/Enterprise/VC/Tools/MSVC/14.31.31103/bin/Hostx86/x64/cl.exe - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: D:/VC2022/Enterprise/VC/Tools/MSVC/14.31.31103/bin/Hostx86/x64/cl.exe - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Detecting Fortran compiler ABI info
  -- Detecting Fortran compiler ABI info - failed
  -- Check for working Fortran compiler: C:/MinGW/bin/gfortran.exe
  -- Check for working Fortran compiler: C:/MinGW/bin/gfortran.exe - broken
  CMake Error at C:/Users/35884/AppData/Local/Temp/pip-build-env-z5e102bv/overlay/Lib/site-packages/cmake/data/share/cmake-3.22/Modules/CMakeTestFortranCom
piler.cmake:61 (message):
    The Fortran compiler

      "C:/MinGW/bin/gfortran.exe"

    is not able to compile a simple test program.

    It fails with the following output:

      Change Dir: C:/Users/35884/AppData/Local/Temp/pip-install-uzaf822v/pylada_c0102c6f43ea4b54846477eba0124932/_skbuild/win-amd64-3.9/cmake-build/CMakeFi
les/CMakeTmp

      Run Build Command(s):C:/Users/35884/AppData/Local/Temp/pip-build-env-z5e102bv/overlay/Lib/site-packages/ninja/data/bin/ninja cmTC_5610c && [1/4] Buil
ding Fortran preprocessed CMakeFiles/cmTC_5610c.dir/testFortranCompiler.f-pp.f
      [2/4] Generating Fortran dyndep file CMakeFiles/cmTC_5610c.dir/Fortran.dd
      [3/4] Building Fortran object CMakeFiles/cmTC_5610c.dir/testFortranCompiler.f.obj
      [4/4] Linking Fortran executable cmTC_5610c.exe
      FAILED: cmTC_5610c.exe
      cmd.exe /C "cd . && C:\MinGW\bin\gfortran.exe  /machine:x64 CMakeFiles/cmTC_5610c.dir/testFortranCompiler.f.obj -o cmTC_5610c.exe -Wl,--out-implib,li
bcmTC_5610c.dll.a -Wl,--major-image-version,0,--minor-image-version,0   && cd ."
      gfortran.exe: error: /machine:x64: No such file or directory
      ninja: build stopped: subcommand failed.

**Comment by ftherrien** [comment]
Hi Yuan, could you send me the error report for Mac or Linux? p2ptrans does not work on Windows, it is for UNIX systems only (MacOS, Linux).

**Comment by yanyuan55** [comment]
Sorry for the late reply. I tried it on a supercomputer that operates Linux and I attached a part of the error report. 

ERROR: Command errored out with exit status 1:
   command: /home/yuayan1/anaconda3/bin/python /home/yuayan1/anaconda3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmpkoz_tv8a
       cwd: /tmp/pip-install-hruhy4k_/pylada_c64ca0dbd0854c93a68a555a38e22950
  Complete output (162 lines):
  Not searching for unused variables given on the command line.
  -- The CXX compiler identification is GNU 4.8.5
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- The Fortran compiler identification is GNU 4.8.5
  -- Detecting Fortran compiler ABI info
  -- Detecting Fortran compiler ABI info - done
  -- Check for working Fortran compiler: /usr/bin/gfortran - skipped
  -- Configuring done
  -- Generating done
  -- Build files have been written to: /tmp/pip-install-hruhy4k_/pylada_c64ca0dbd0854c93a68a555a38e22950/_cmake_test_compile/build
  -- The C compiler identification is GNU 4.8.5
  -- The CXX compiler identification is GNU 4.8.5
  -- The Fortran compiler identification is GNU 4.8.5
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /usr/bin/cc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Detecting Fortran compiler ABI info
  -- Detecting Fortran compiler ABI info - done
  -- Check for working Fortran compiler: /usr/bin/gfortran - skipped
  -- The CXX compiler identification is GNU 4.8.5
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Configuring done
  -- Generating done
  CMake Warning:
    Manually-specified variables were not used by the project:

      CMAKE_C_COMPILER


  -- Build files have been written to: /tmp/pip-install-hruhy4k_/pylada_c64ca0dbd0854c93a68a555a38e22950/_skbuild/linux-x86_64-3.9/cmake-build/eigen
  [1/8] Creating directories for 'Eigen'
  [2/8] Performing download step (download, verify and extract) for 'Eigen'
  -- Downloading...
     dst='/tmp/pip-install-hruhy4k_/pylada_c64ca0dbd0854c93a68a555a38e22950/_skbuild/linux-x86_64-3.9/cmake-build/eigen/external/src/eigen-3.3.7.tar.gz'
     timeout='none'
     inactivity timeout='none'
  -- Using src='https://gitlab.com/libeigen/eigen/-/archive/3.3.7/eigen-3.3.7.tar.gz'
  -- verifying file...
         file='/tmp/pip-install-hruhy4k_/pylada_c64ca0dbd0854c93a68a555a38e22950/_skbuild/linux-x86_64-3.9/cmake-build/eigen/external/src/eigen-3.3.7.tar.gz'
  -- Downloading... done
  -- extracting...
       src='/tmp/pip-install-hruhy4k_/pylada_c64ca0dbd0854c93a68a555a38e22950/_skbuild/linux-x86_64-3.9/cmake-build/eigen/external/src/eigen-3.3.7.tar.gz'
       dst='/tmp/pip-install-hruhy4k_/pylada_c64ca0dbd0854c93a68a555a38e22950/_skbuild/linux-x86_64-3.9/cmake-build/eigen/external/src/Eigen'
  -- extracting... [tar xfz]
  -- extracting... [analysis]
  -- extracting... [rename]
  -- extracting... [clean up]
  -- extracting... done
  [3/8] No update step for 'Eigen'
  [4/8] No patch step for 'Eigen'
  [5/8] Performing configure step for 'Eigen'
  FAILED: external/src/Eigen-stamp/Eigen-configure /tmp/pip-install-hruhy4k_/pylada_c64ca0dbd0854c93a68a555a38e22950/_skbuild/linux-x86_64-3.9/cmake-build/eigen/external/src/Eigen-stamp/Eigen-configure
  cd /tmp/pip-install-hruhy4k_/pylada_c64ca0dbd0854c93a68a555a38e22950/_skbuild/linux-x86_64-3.9/cmake-build/eigen/external/src/Eigen-build && /tmp/pip-build-env-f613f4jk/overlay/lib/python3.9/site-packages/cmake/data/bin/cmake -DCMAKE_INSTALL_PREFIX=/tmp/pip-install-hruhy4k_/pylada_c64ca0dbd0854c93a68a555a38e22950/_skbuild/linux-x86_64-3.9/cmake-build/eigen -DCMAKE_CXX_COMPILER=/usr/bin/c++ -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DEIGEN_BUILD_PKGCONFIG=OFF -DBUILD_TESTING=OFF -GNinja /tmp/pip-install-hruhy4k_/pylada_c64ca0dbd0854c93a68a555a38e22950/_skbuild/linux-x86_64-3.9/cmake-build/eigen/external/src/Eigen && /tmp/pip-build-env-f613f4jk/overlay/lib/python3.9/site-packages/cmake/data/bin/cmake -E touch /tmp/pip-install-hruhy4k_/pylada_c64ca0dbd0854c93a68a555a38e22950/_skbuild/linux-x86_64-3.9/cmake-build/eigen/external/src/Eigen-stamp/Eigen-configure
  -- The C compiler identification is GNU 4.8.5
  -- The CXX compiler identification is GNU 4.8.5
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /usr/bin/cc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  CMake Deprecation Warning at CMakeLists.txt:3 (cmake_minimum_required):
    Compatibility with CMake < 2.8.12 will be removed from a future version of
    CMake.

    Update the VERSION argument <min> value or use a ...<max> suffix to tell
    CMake that the project does not need compatibility with older versions.


  -- Performing Test EIGEN_COMPILER_SUPPORT_CPP11
  -- Performing Test EIGEN_COMPILER_SUPPORT_CPP11 - Success
  -- Performing Test COMPILER_SUPPORT_std=cpp03
  -- Performing Test COMPILER_SUPPORT_std=cpp03 - Success
  -- Performing Test standard_math_library_linked_to_automatically
  -- Performing Test standard_math_library_linked_to_automatically - Failed
  -- Performing Test standard_math_library_linked_to_as_m
  -- Performing Test standard_math_library_linked_to_as_m - Failed
  CMake Error at CMakeLists.txt:111 (message):
    Can't link to the standard math library.  Please report to the Eigen
    developers, telling them about your platform.


  -- Configuring incomplete, errors occurred!
  See also "/tmp/pip-install-hruhy4k_/pylada_c64ca0dbd0854c93a68a555a38e22950/_skbuild/linux-x86_64-3.9/cmake-build/eigen/external/src/Eigen-build/CMakeFiles/CMakeOutput.log".
  See also "/tmp/pip-install-hruhy4k_/pylada_c64ca0dbd0854c93a68a555a38e22950/_skbuild/linux-x86_64-3.9/cmake-build/eigen/external/src/Eigen-build/CMakeFiles/CMakeError.log".
  ninja: build stopped: subcommand failed.
  -- Install configuration: "Release"
  CMake Error at CMakeLists.txt:46 (find_package):
    Could not find a package configuration file provided by "Eigen3" with any
    of the following names:

      Eigen3Config.cmake
      eigen3-config.cmake

    Add the installation prefix of "Eigen3" to CMAKE_PREFIX_PATH or set
    "Eigen3_DIR" to a directory containing one of the above files.  If "Eigen3"
    provides a separate development package or SDK, be sure it has been
    installed.


  -- Configuring incomplete, errors occurred!
  See also "/tmp/pip-install-hruhy4k_/pylada_c64ca0dbd0854c93a68a555a38e22950/_skbuild/linux-x86_64-3.9/cmake-build/CMakeFiles/CMakeOutput.log".
    File "/tmp/pip-build-env-f613f4jk/overlay/lib/python3.9/site-packages/skbuild/setuptools_wrap.py", line 588, in setup
      env = cmkr.configure(cmake_args,
    File "/tmp/pip-build-env-f613f4jk/overlay/lib/python3.9/site-packages/skbuild/cmaker.py", line 289, in configure
      raise SKBuildError(


  --------------------------------------------------------------------------------
  -- Trying "Ninja" generator
  --------------------------------
  ---------------------------
  ----------------------
  -----------------
  ------------
  -------
  --
  --
  -------
  ------------
  -----------------
  ----------------------
  ---------------------------
  --------------------------------
  -- Trying "Ninja" generator - success
  --------------------------------------------------------------------------------

  Configuring Project
    Working directory:
      /tmp/pip-install-hruhy4k_/pylada_c64ca0dbd0854c93a68a555a38e22950/_skbuild/linux-x86_64-3.9/cmake-build
    Command:
      cmake /tmp/pip-install-hruhy4k_/pylada_c64ca0dbd0854c93a68a555a38e22950 -G Ninja -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-install-hruhy4k_/pylada_c64ca0dbd0854c93a68a555a38e22950/_skbuild/linux-x86_64-3.9/cmake-install -DPYTHON_EXECUTABLE:FILEPATH=/home/yuayan1/anaconda3/bin/python -DPYTHON_VERSION_STRING:STRING=3.9.7 -DPYTHON_INCLUDE_DIR:PATH=/home/yuayan1/anaconda3/include/python3.9 -DPYTHON_LIBRARY:FILEPATH=/home/yuayan1/anaconda3/lib/libpython3.9.so -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/pip-build-env-f613f4jk/overlay/lib/python3.9/site-packages/skbuild/resources/cmake -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/pip-build-env-f613f4jk/overlay/lib/python3.9/site-packages/ninja/data/bin/ninja -DCMAKE_BUILD_TYPE:STRING=Release

  Traceback (most recent call last):

  An error occurred while configuring with CMake.
    Command:
      cmake /tmp/pip-install-hruhy4k_/pylada_c64ca0dbd0854c93a68a555a38e22950 -G Ninja -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-install-hruhy4k_/pylada_c64ca0dbd0854c93a68a555a38e22950/_skbuild/linux-x86_64-3.9/cmake-install -DPYTHON_EXECUTABLE:FILEPATH=/home/yuayan1/anaconda3/bin/python -DPYTHON_VERSION_STRING:STRING=3.9.7 -DPYTHON_INCLUDE_DIR:PATH=/home/yuayan1/anaconda3/include/python3.9 -DPYTHON_LIBRARY:FILEPATH=/home/yuayan1/anaconda3/lib/libpython3.9.so -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/pip-build-env-f613f4jk/overlay/lib/python3.9/site-packages/skbuild/resources/cmake -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/pip-build-env-f613f4jk/overlay/lib/python3.9/site-packages/ninja/data/bin/ninja -DCMAKE_BUILD_TYPE:STRING=Release
    Source directory:
      /tmp/pip-install-hruhy4k_/pylada_c64ca0dbd0854c93a68a555a38e22950
    Working directory:
      /tmp/pip-install-hruhy4k_/pylada_c64ca0dbd0854c93a68a555a38e22950/_skbuild/linux-x86_64-3.9/cmake-build
  Please see CMake's output for more information.
  ----------------------------------------
  ERROR: Failed building wheel for pylada

**Comment by ftherrien** [comment]
Hi Yuan,

Can you show me the content of these two files:

/tmp/pip-install-hruhy4k_/pylada_c64ca0dbd0854c93a68a555a38e22950/skbuild/linux-x86_64-3.9/cmake-build/eigen/external/src/Eigen-build/CMakeFiles/CMakeOutput.log

/tmp/pip-install-hruhy4k/pylada_c64ca0dbd0854c93a68a555a38e22950/_skbuild/linux-x86_64-3.9/cmake-build/eigen/external/src/Eigen-build/CMakeFiles/CMakeError.log

Can you try to install pylada (that is what is failing)?
First try:
`
pip install git+https://github.com/pylada/pylada-light`

If you get the same error, try:

`pip install git@github.com:pylada/pylada-light.git@eigen-issue`

**Comment by yanyuan55** [comment]
I cannot show you these two files because I did not have access permission.
does this software depend on a specific instruction set?


At the beginning, I cannot install pylada with the same error information with p2ptrans. 
And then, I successfully install pylada after I installed CMake. After I installed CMake,  I am trying to install p2ptrans again. But failed with following error information:

  /tmp/ccLJuPjY.s:25109: Error: unknown .loc sub-directive `view'
  /tmp/ccLJuPjY.s:25109: Error: unknown pseudo-op: `.lvu7764'
  /tmp/ccLJuPjY.s:25115: Error: unknown .loc sub-directive `view'
  /tmp/ccLJuPjY.s:25115: Error: unknown pseudo-op: `.lvu7765'
  /tmp/ccLJuPjY.s:25120: Error: unknown .loc sub-directive `view'
  /tmp/ccLJuPjY.s:25120: Error: unknown pseudo-op: `.lvu7766'
  /tmp/ccLJuPjY.s:25130: Error: unknown .loc sub-directive `view'
  /tmp/ccLJuPjY.s:25130: Error: unknown pseudo-op: `.lvu7767'
  /tmp/ccLJuPjY.s:25137: Error: unknown .loc sub-directive `view'
  /tmp/ccLJuPjY.s:25137: Error: unknown pseudo-op: `.lvu7768'
  /tmp/ccLJuPjY.s:25146: Error: unknown .loc sub-directive `view'
  /tmp/ccLJuPjY.s:25146: Error: unknown pseudo-op: `.lvu7769'
  /tmp/ccLJuPjY.s:25151: Error: unknown .loc sub-directive `view'
  /tmp/ccLJuPjY.s:25151: Error: unknown pseudo-op: `.lvu7770'
  /tmp/ccLJuPjY.s:25154: Error: unknown .loc sub-directive `view'
  /tmp/ccLJuPjY.s:25154: Error: unknown pseudo-op: `.lvu7771'
  /tmp/ccLJuPjY.s:25160: Error: unknown .loc sub-directive `view'
  /tmp/ccLJuPjY.s:25160: Error: unknown pseudo-op: `.lvu7772'
  /tmp/ccLJuPjY.s:25165: Error: unknown .loc sub-directive `view'
  /tmp/ccLJuPjY.s:25165: Error: unknown pseudo-op: `.lvu7773'
  /tmp/ccLJuPjY.s:25174: Error: unknown .loc sub-directive `view'
  /tmp/ccLJuPjY.s:25174: Error: unknown pseudo-op: `.lvu7774'
  /tmp/ccLJuPjY.s:25179: Error: unknown .loc sub-directive `view'
  /tmp/ccLJuPjY.s:25179: Error: unknown pseudo-op: `.lvu7775'
  /tmp/ccLJuPjY.s:25188: Error: unknown .loc sub-directive `view'
  /tmp/ccLJuPjY.s:25188: Error: unknown pseudo-op: `.lvu7776'
  /tmp/ccLJuPjY.s:25193: Error: unknown .loc sub-directive `view'
  /tmp/ccLJuPjY.s:25193: Error: unknown pseudo-op: `.lvu7777'
  /tmp/ccLJuPjY.s:25199: Error: unknown .loc sub-directive `view'
  /tmp/ccLJuPjY.s:25199: Error: unknown pseudo-op: `.lvu7778'
  /tmp/ccLJuPjY.s:25202: Error: unknown .loc sub-directive `view'
  /tmp/ccLJuPjY.s:25202: Error: unknown pseudo-op: `.lvu7779'
  /tmp/ccLJuPjY.s:25204: Error: unknown .loc sub-directive `view'
  /tmp/ccLJuPjY.s:25204: Error: unknown pseudo-op: `.lvu7780'
  /tmp/ccLJuPjY.s:25205: Error: unknown .loc sub-directive `view'
  /tmp/ccLJuPjY.s:25205: Error: unknown pseudo-op: `.lvu7781'
  /tmp/ccLJuPjY.s:25206: Error: unknown .loc sub-directive `view'
  /tmp/ccLJuPjY.s:25206: Error: unknown pseudo-op: `.lvu7782'
  /tmp/ccLJuPjY.s:25207: Error: unknown .loc sub-directive `view'
  /tmp/ccLJuPjY.s:25207: Error: unknown pseudo-op: `.lvu7783'
  /tmp/ccLJuPjY.s:25208: Error: unknown .loc sub-directive `view'
  /tmp/ccLJuPjY.s:25208: Error: unknown pseudo-op: `.lvu7784'
  /tmp/ccLJuPjY.s:25211: Error: unknown .loc sub-directive `view'
  /tmp/ccLJuPjY.s:25211: Error: unknown pseudo-op: `.lvu7785'
  /tmp/ccLJuPjY.s:25216: Error: unknown .loc sub-directive `view'
  /tmp/ccLJuPjY.s:25216: Error: unknown pseudo-op: `.lvu7786'
  /tmp/ccLJuPjY.s:25221: Error: unknown .loc sub-directive `view'
  /tmp/ccLJuPjY.s:25221: Error: unknown pseudo-op: `.lvu7787'
  /tmp/ccLJuPjY.s:25224: Error: unknown .loc sub-directive `view'
  /tmp/ccLJuPjY.s:25224: Error: unknown pseudo-op: `.lvu7788'
  /tmp/ccLJuPjY.s:25228: Error: unknown .loc sub-directive `view'
  /tmp/ccLJuPjY.s:25228: Error: unknown pseudo-op: `.lvu7789'
  /tmp/ccLJuPjY.s:25233: Error: unknown .loc sub-directive `view'
  /tmp/ccLJuPjY.s:25233: Error: unknown pseudo-op: `.lvu7790'
  /tmp/ccLJuPjY.s:25234: Error: unknown .loc sub-directive `view'
  /tmp/ccLJuPjY.s:25234: Error: unknown pseudo-op: `.lvu7791'
  /tmp/ccLJuPjY.s:25251: Error: unknown .loc sub-directive `view'
  /tmp/ccLJuPjY.s:25251: Error: unknown pseudo-op: `.lvu7792'
  /tmp/ccLJuPjY.s:25252: Error: unknown .loc sub-directive `view'
  /tmp/ccLJuPjY.s:25252: Error: unknown pseudo-op: `.lvu7793'
  /tmp/ccLJuPjY.s:25255: Error: unknown .loc sub-directive `view'
  /tmp/ccLJuPjY.s:25255: Error: unknown pseudo-op: `.lvu7794'
  /tmp/ccLJuPjY.s:25264: Error: unknown .loc sub-directive `view'
  /tmp/ccLJuPjY.s:25264: Error: unknown pseudo-op: `.lvu7795'
  /tmp/ccLJuPjY.s:25265: Error: unknown .loc sub-directive `view'
  /tmp/ccLJuPjY.s:25265: Error: unknown pseudo-op: `.lvu7796'
  /tmp/ccLJuPjY.s:25269: Error: unknown .loc sub-directive `view'
  /tmp/ccLJuPjY.s:25269: Error: unknown pseudo-op: `.lvu7797'
  /tmp/ccLJuPjY.s:25270: Error: unknown .loc sub-directive `view'
  /tmp/ccLJuPjY.s:25270: Error: unknown pseudo-op: `.lvu7798'
  /tmp/ccLJuPjY.s:25273: Error: unknown .loc sub-directive `view'
  /tmp/ccLJuPjY.s:25273: Error: unknown pseudo-op: `.lvu7799'
  /tmp/ccLJuPjY.s:25282: Error: unknown .loc sub-directive `view'
  /tmp/ccLJuPjY.s:25282: Error: unknown pseudo-op: `.lvu7800'
  /tmp/ccLJuPjY.s:25283: Error: unknown .loc sub-directive `view'
  /tmp/ccLJuPjY.s:25283: Error: unknown pseudo-op: `.lvu7801'
  /tmp/ccLJuPjY.s:25287: Error: unknown .loc sub-directive `view'
  /tmp/ccLJuPjY.s:25287: Error: unknown pseudo-op: `.lvu7802'
  /tmp/ccLJuPjY.s:25290: Error: unknown .loc sub-directive `view'
  /tmp/ccLJuPjY.s:25290: Error: unknown pseudo-op: `.lvu7803'
  /tmp/ccLJuPjY.s:25296: Error: unknown .loc sub-directive `view'
  /tmp/ccLJuPjY.s:25296: Error: unknown pseudo-op: `.lvu7804'
  /tmp/ccLJuPjY.s:25297: Error: unknown .loc sub-directive `view'
  /tmp/ccLJuPjY.s:25297: Error: unknown pseudo-op: `.lvu7805'
  /tmp/ccLJuPjY.s:25301: Error: unknown .loc sub-directive `view'
  /tmp/ccLJuPjY.s:25301: Error: unknown pseudo-op: `.lvu7806'
  /tmp/ccLJuPjY.s:25304: Error: unknown .loc sub-directive `view'
  /tmp/ccLJuPjY.s:25304: Error: unknown pseudo-op: `.lvu7807'
  /tmp/ccLJuPjY.s:25310: Error: unknown .loc sub-directive `view'
  /tmp/ccLJuPjY.s:25310: Error: unknown pseudo-op: `.lvu7808'
  /tmp/ccLJuPjY.s:25311: Error: unknown .loc sub-directive `view'
  /tmp/ccLJuPjY.s:25311: Error: unknown pseudo-op: `.lvu7809'
  /tmp/ccLJuPjY.s:25315: Error: unknown .loc sub-directive `view'
  /tmp/ccLJuPjY.s:25315: Error: unknown pseudo-op: `.lvu7810'
  /tmp/ccLJuPjY.s:25321: Error: unknown .loc sub-directive `view'
  /tmp/ccLJuPjY.s:25321: Error: unknown pseudo-op: `.lvu7811'
  /tmp/ccLJuPjY.s:25322: Error: unknown .loc sub-directive `view'
  /tmp/ccLJuPjY.s:25322: Error: unknown pseudo-op: `.lvu7812'
  /tmp/ccLJuPjY.s:25326: Error: unknown .loc sub-directive `view'
  /tmp/ccLJuPjY.s:25326: Error: unknown pseudo-op: `.lvu7813'
  /tmp/ccLJuPjY.s:25332: Error: unknown .loc sub-directive `view'
  /tmp/ccLJuPjY.s:25332: Error: unknown pseudo-op: `.lvu7814'
  /tmp/ccLJuPjY.s:25333: Error: unknown .loc sub-directive `view'
  /tmp/ccLJuPjY.s:25333: Error: unknown pseudo-op: `.lvu7815'
  /tmp/ccLJuPjY.s:25337: Error: unknown .loc sub-directive `view'
  /tmp/ccLJuPjY.s:25337: Error: unknown pseudo-op: `.lvu7816'
  /tmp/ccLJuPjY.s:25340: Error: unknown .loc sub-directive `view'
  /tmp/ccLJuPjY.s:25340: Error: unknown pseudo-op: `.lvu7817'
  /tmp/ccLJuPjY.s:25341: Error: unknown .loc sub-directive `view'
  /tmp/ccLJuPjY.s:25341: Error: unknown pseudo-op: `.lvu7818'
  /tmp/ccLJuPjY.s:25345: Error: unknown .loc sub-directive `view'
  /tmp/ccLJuPjY.s:25345: Error: unknown pseudo-op: `.lvu7819'
  /tmp/ccLJuPjY.s:25348: Error: unknown .loc sub-directive `view'
  /tmp/ccLJuPjY.s:25348: Error: unknown pseudo-op: `.lvu7820'
  /tmp/ccLJuPjY.s:25351: Error: unknown .loc sub-directive `view'
  /tmp/ccLJuPjY.s:25351: Error: unknown pseudo-op: `.lvu7821'
  /tmp/ccLJuPjY.s:25355: Error: unknown .loc sub-directive `view'
  /tmp/ccLJuPjY.s:25355: Error: unknown pseudo-op: `.lvu7822'
  /tmp/ccLJuPjY.s:25358: Error: unknown .loc sub-directive `view'
  /tmp/ccLJuPjY.s:25358: Error: unknown pseudo-op: `.lvu7823'
  /tmp/ccLJuPjY.s:25360: Error: unknown .loc sub-directive `view'
  /tmp/ccLJuPjY.s:25360: Error: unknown pseudo-op: `.lvu7824'
  /tmp/ccLJuPjY.s:25361: Error: unknown .loc sub-directive `view'
  /tmp/ccLJuPjY.s:25361: Error: unknown pseudo-op: `.lvu7825'
  /tmp/ccLJuPjY.s:25362: Error: unknown .loc sub-directive `view'
  /tmp/ccLJuPjY.s:25362: Error: unknown pseudo-op: `.lvu7826'
  /tmp/ccLJuPjY.s:25363: Error: unknown .loc sub-directive `view'
  /tmp/ccLJuPjY.s:25363: Error: unknown pseudo-op: `.lvu7827'
  /tmp/ccLJuPjY.s:25364: Error: unknown .loc sub-directive `view'
  /tmp/ccLJuPjY.s:25364: Error: unknown pseudo-op: `.lvu7828'
  /tmp/ccLJuPjY.s:25366: Error: unknown .loc sub-directive `view'
  /tmp/ccLJuPjY.s:25366: Error: unknown pseudo-op: `.lvu7829'
  /tmp/ccLJuPjY.s:25370: Error: unknown .loc sub-directive `view'
  /tmp/ccLJuPjY.s:25370: Error: unknown pseudo-op: `.lvu7830'
  INFO:
  ########### EXT COMPILER OPTIMIZATION ###########
  INFO: Platform      :
    Architecture: x64
    Compiler    : gcc

  CPU baseline  :
    Requested   : 'min'
    Enabled     : none
    Flags       : none
    Extra checks: none

  CPU dispatch  :
    Requested   : 'max -xop -fma4'
    Enabled     : none
    Generated   : none
  INFO: CCompilerOpt.cache_flush[817] : write cache to path -> /tmp/pip-req-build-rvemxhos/build/temp.linux-x86_64-3.8/ccompiler_opt_cache_ext.py
  error: Command "gcc -pthread -B /usr/local/easybuild-2019/easybuild/software/core/anaconda3/2021.05/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ibuild/src.linux-x86_64-3.8/build/src.linux-x86_64-3.8/p2ptrans -I/tmp/pip-build-env-qu1vi7nr/overlay/lib/python3.8/site-packages/numpy/core/include -Ibuild/src.linux-x86_64-3.8/numpy/distutils/include -I/usr/local/easybuild-2019/easybuild/software/core/anaconda3/2021.05/include/python3.8 -c build/src.linux-x86_64-3.8/build/src.linux-x86_64-3.8/p2ptrans/fortranobject.c -o build/temp.linux-x86_64-3.8/build/src.linux-x86_64-3.8/build/src.linux-x86_64-3.8/p2ptrans/fortranobject.o -MMD -MF build/temp.linux-x86_64-3.8/build/src.linux-x86_64-3.8/build/src.linux-x86_64-3.8/p2ptrans/fortranobject.o.d" failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for p2ptrans

**Comment by ftherrien** [comment]
Hi Yuan,

1. Were you able to install pylada with the first command: `pip install git+https://github.com/pylada/pylada-light` or the second command `pip install git@github.com:pylada/pylada-light.git@eigen-issue`?

2. These seem to be assembler errors, is it possible that you changed some of the modules that you had loaded when you installed pylada?

If you can install pylada, there is no reason why p2ptrans would fail to install

**Comment by yanyuan55** [comment]
1:  
I install with this command:    pip install git+https://github.com/pylada/pylada-light  
I tried pip install git@github.com:pylada/pylada-light.git@eigen-issue,   with following error information.
ERROR: Invalid requirement: 'git@github.com:pylada/pylada-light.git@eigen-issue'
Hint: It looks like a path. File 'git@github.com:pylada/pylada-light.git@eigen-issue' does not exist.

2:
Before I install pylada, I module load CMake and anacanda3. 

I get confused about it. When I install pylada, I think I should be able to install p2ptrans, But failed.

**Comment by ftherrien** [comment]
Hi Yuan,

Yes sorry there was mistake in the path: `pip install git+https://github.com/pylada/pylada-light@eigen-issue`

Can you install pylada and then immediately install p2ptrans and show me the full output with the two commands?

```
pip install git+https://github.com/pylada/pylada-light
pip install git+https://github.com/ftherrien/p2ptrans
```

**Comment by yanyuan55** [comment]
Hi Félix,

Thank you very much for your patience. I stored the full output information in two attached files. 

[pylada.log](https://github.com/ftherrien/p2ptrans/files/8137201/pylada.log)
[p2ptrans.log](https://github.com/ftherrien/p2ptrans/files/8137202/p2ptrans.log)

I

**Comment by yanyuan55** [comment]
Hi Félix,

I solved this problem. 

The service team from High-Performance Computing at the University of Melbourne helped me with following install steps：


module load gcccore/10.2.0
module load python/3.8.6
module load foss/2020b
module load scipy-bundle/2020.11-python-3.8.6
module load scikit-build/0.11.1-python-3.8.6
pip install git+https://github.com/ftherrien/p2ptrans --user

**Comment by ftherrien** [comment]
That's great, I am glad you were able to resolve this!
