### ISSUE TITLE
Crashes with error for test run 

### ISSUE THREAD

**Issue by nityasagarjena** [ftherrien/p2ptrans#33]
p2ptrans -I POSCAR_BCC -F POSCAR_FCC 
Traceback (most recent call last):
  File "/cfs/klemming/projects/snic/theophys/x_njena/anaconda3/bin/p2ptrans", line 6, in <module>
    from p2ptrans import *
  File "/cfs/klemming/home/n/njena/.local/lib/python3.10/site-packages/p2ptrans/__init__.py", line 4, in <module>
    from . import display
  File "/cfs/klemming/home/n/njena/.local/lib/python3.10/site-packages/p2ptrans/display.py", line 4, in <module>
    from .config import *
  File "/cfs/klemming/home/n/njena/.local/lib/python3.10/site-packages/p2ptrans/config.py", line 1, in <module>
    from pylada.crystal import Structure, primitive, gruber, read, write, supercell, space_group, into_cell
  File "/cfs/klemming/home/n/njena/.local/lib/python3.10/site-packages/pylada/__init__.py", line 127, in <module>
    from . import error, crystal, physics, misc, tools, ewald, decorations, periodic_table, vasp, \
  File "/cfs/klemming/home/n/njena/.local/lib/python3.10/site-packages/pylada/espresso/__init__.py", line 35, in <module>
    from .structure_handling import read_structure
  File "/cfs/klemming/home/n/njena/.local/lib/python3.10/site-packages/pylada/espresso/structure_handling.py", line 240
    %(atom.type, atom.pos[0],atom.pos[1], atom.pos[2],
    ^
SyntaxError: invalid syntax

**Comment by ftherrien** [comment]
Again I am not sure you succeded in you installation in the first place #31. So I will close #32 and #33 and let's discuss in #31
