### ISSUE TITLE
Update version so pip -u will work

### ISSUE THREAD

**Issue by Ash-Pera** [ftherrien/p2ptrans#9]
Hi Felix,
Could you update the version of p2p when you make bugfixes so that pip --upgrade will appropriately update the software?

**Comment by ftherrien** [comment]
Ash,

That will not work until I add p2ptrans on PyPI and I actually update the version every time I make a significant modification. As soon as the 2D (interface) portion of the code is up and running, I intend to upload version 1.0 (it is 0.0 at the moment) on PyPI at which point you will be able to do: pip install p2ptrans and pip install --upgrade p2ptrans.

You are right that I should probably change minor versions 0.x when I make important feature changes or bug fixes, this has been difficult as I am quickly making a lot of changes and since the versioning doesn't really matter yet...

I will rename this issue: "Adding p2ptrans to PyPI"  as I think this is the underlying problem.

**Comment by yuefengzhang** [comment]
Hi, I'm trying to use the p2ptrans，but I'm encountering the following error: ”ImportError: cannot import name 'hungarian' from 'p2ptrans.fmodules' (/home/yuefzhang3/scratch/software/miniconda/lib/python3.11/site-packages/p2ptrans/fmodules.cpython-311-x86_64-linux-gnu.so)". Could you please help me understand what might be causing this issue and how I can resolve it? Any guidance or assistance you can provide would be greatly appreciated.
Thank you in advance for your time and support.

**Comment by ftherrien** [comment]
@yuefengzhang this error comes up if you use numpy 1.26.3 or 1.26.4, any other version before or after will work.

See:

https://github.com/ftherrien/p2ptrans/issues/34#issuecomment-2045830309

Let me know if that works for you.

**Comment by yuefengzhang** [comment]
Hi,
    Thank you very much for your previous response. I have used NumPy version 1.26.0, but I am still encountering the error "cannot import name 'hungarian' from 'p2ptrans.fmodules'". I was wondering if you could help me understand the potential reason for this issue.
Thank you again for your assistance. I look forward to your reply.
[cid:4b4ee0c1-810e-45d0-addb-7782183d2317]
Best wishes,
Yuefeng Zhang

________________________________
发件人: Félix Therrien ***@***.***>
发送时间: 2024年6月7日 下午 11:07
收件人: ftherrien/p2ptrans ***@***.***>
抄送: ZHANG Yuefeng ***@***.***>; Mention ***@***.***>
主题: [Ext] Re: [ftherrien/p2ptrans] Adding p2ptrans to PyPl (#9)

CAUTION: External email. Do not reply, click on links or open attachments unless you recognize the sender and know the content is safe.


@yuefengzhang<https://github.com/yuefengzhang> this error comes up if you use numpy 1.26.3 or 1.26.4, any other version before or after will work.

See:

#34 (comment)<https://github.com/ftherrien/p2ptrans/issues/34#issuecomment-2045830309>

Let me know if that works for you.

―

**Comment by ftherrien** [comment]
Did you reinstall using that version?

**Comment by yuefengzhang** [comment]
Hi, thank you again for your response. I have reinstalled numpy 1.26.0 as well as p2ptrans, but I'm still encountering the same error. I will keep trying to resolve this issue.
I'd appreciate if you could provide any additional guidance you may have. Your assistance is greatly valued. Have a good day.
Best wishes,
Yuefeng Zhang
________________________________
发件人: Félix Therrien ***@***.***>
发送时间: 2024年6月8日 上午 12:39
收件人: ftherrien/p2ptrans ***@***.***>
抄送: ZHANG Yuefeng ***@***.***>; Mention ***@***.***>
主题: [Ext] Re: [ftherrien/p2ptrans] Adding p2ptrans to PyPl (#9)

CAUTION: External email. Do not reply, click on links or open attachments unless you recognize the sender and know the content is safe.


Did you reinstall using that version?

―

**Comment by ftherrien** [comment]
Could you run the following and copy the output from your terminal here:

```
python -m pip freeze | grep -E "numpy|p2ptrans"
which python
python -c "import numpy; numpy.__version__"
python -c "import p2ptrans"
```

**Comment by yuefengzhang** [comment]
Hi，I have copied the above command and the terminal output is as follows. It's the same question as before. I have tried many times and still have this problem. Can you help me figure out what the reason is? Thank you.
[cid:3a440eaa-b5cc-4c6e-a8da-ce90a740ae23]
________________________________
发件人: Félix Therrien ***@***.***>
发送时间: 2024年6月9日 上午 2:38
收件人: ftherrien/p2ptrans ***@***.***>
抄送: ZHANG Yuefeng ***@***.***>; Mention ***@***.***>
主题: [Ext] Re: [ftherrien/p2ptrans] Adding p2ptrans to PyPl (#9)

CAUTION: External email. Do not reply, click on links or open attachments unless you recognize the sender and know the content is safe.


Could you run the following and copy the output from your terminal here:

python -m pip freeze | grep -E "numpy|p2ptrans"
which python
python -c "import numpy; numpy.__version__"
python -c "import p2ptrans"


―

**Comment by ftherrien** [comment]
I don't see the output from the terminal

**Comment by yuefengzhang** [comment]
Run "python -m pip freeze | grep -E "numpy|p2ptrans",
The output is numpy==1.26.0
p2ptrans @ ***@***.***
Run "which python"
The output is  /gpfs1/home/yuefzhang3/miniconda3/bin/python
Run"python -c "import numpy; numpy.__version__"
The output is none
Run " python -c "import p2ptrans"
The output is "Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/gpfs1/home/yuefzhang3/miniconda3/lib/python3.11/site-packages/p2ptrans/__init__.py", line 5, in <module>
    from . import interfaces
  File "/gpfs1/home/yuefzhang3/miniconda3/lib/python3.11/site-packages/p2ptrans/interfaces.py", line 10, in <module>
    from .core import makeSphere, find_cell, makeStructures, switchDispStruc, find_periodicity
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs1/home/yuefzhang3/miniconda3/lib/python3.11/site-packages/p2ptrans/core.py", line 8, in <module>
    from .fmodules import hungarian as lap
ImportError: cannot import name 'hungarian' from 'p2ptrans.fmodules' (/gpfs1/home/yuefzhang3/miniconda3/lib/python3.11/site-packages/p2ptrans/fmodules.cpython-311-x86_64-linux-gnu.so)"
If I still have not understood your meaning, please do let me know. Thanks.
Best wishes
________________________________
发件人: Félix Therrien ***@***.***>
发送时间: 2024年6月9日 上午 10:22
收件人: ftherrien/p2ptrans ***@***.***>
抄送: ZHANG Yuefeng ***@***.***>; Mention ***@***.***>
主题: [Ext] Re: [ftherrien/p2ptrans] Adding p2ptrans to PyPl (#9)

CAUTION: External email. Do not reply, click on links or open attachments unless you recognize the sender and know the content is safe.


I don't see the output from the terminal

―

**Comment by ftherrien** [comment]
Can you try:

```
pip install --upgrade numpy==1.26.0
pip uninstall p2ptrans
pip install scikit-build
pip install --no-use-pep517 git+https://github.com/ftherrien/p2ptrans
```

**Comment by yuefengzhang** [comment]
Hi, it worked! Thank you so much for your invaluable assistance. Your help is greatly appreciated! Have a good day.

Best wishes,
Yuefeng Zhang
________________________________
发件人: Félix Therrien ***@***.***>
发送时间: 2024年6月12日 上午 5:17
收件人: ftherrien/p2ptrans ***@***.***>
抄送: ZHANG Yuefeng ***@***.***>; Mention ***@***.***>
主题: [Ext] Re: [ftherrien/p2ptrans] Adding p2ptrans to PyPl (#9)

CAUTION: External email. Do not reply, click on links or open attachments unless you recognize the sender and know the content is safe.


Can you try:

pip install --upgrade numpy==1.26.0
pip uninstall p2ptrans
pip install scikit-build
pip install --no-use-pep517 git+https://github.com/ftherrien/p2ptrans


―

**Comment by ftherrien** [comment]
Great! Happy to help, let me know if you have other questions
